# Links on sidebar
menu:
  Home: /
  Archive: /archives/
  # Tags: /tags/
  # Categories: /categories/
  Logbooks: /logbooks/
  About: /about/

# Pictures shown on the sidebar
# Use the absolute URL after generating
avatar: /assets/gremlin.jpg
sidebar_background: /assets/header.jpg

rss: /atom.xml

# Content
excerpt_link: Read On Â»

# Will be shown on the bottom.
## To add new icon, just copy .svg to source/assets/ and add entries below.
media:

Github: https://github.com/nameoverflow
Thingiverse: https://www.thingiverse.com/sunbane/designs

source_han_font: true

# Disqus settings
disqus:
  # 'disabled' | 'all' | 'post'
  enable: disabled
  # Shortname of your disqus website.
  # See disqus admin
  shortname:

# Miscellaneous
favicon:
